# Generated by Django 5.0.2 on 2024-02-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_cmsslider_cms_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmsslider',
            name='cms_css',
        ),
    ]
